### ISSUE TITLE
Image Save with Prompt Data - Seed input non-functional

### ISSUE THREAD

**Issue by JHNewton** [wallish77/wlsh_nodes#3]
Love this idea, but when I change the  seed widget to an input, nothing will connect to it.  I tried your seed-to-number node as well.

**Comment by wallish77** [comment]
So it seems that it is only working with the WAS Node Suite's "Seed" node (under Numbers category), which strangely enough DOESN'T attach to the default KSampler node (if Seed is changed to an input).  Looks like the 'seed' input on the KSampler is now an INT type while both my node and WAS are "SEED" type.  Seed to Number can conver the WAS "SEED" type to INT, which lets it plug in to the default KSampler, but won't connect it to the image save. 

I can change Image Save to receive a standard INT so that Primitives can be used, but that might break a bunch of workflows.  I _think_ that the default Comfy node used to use SEED type as well and that WAS's behavior might be a carry-over from that.  Since I was using the WAS Seed node, I modified mine to use that as well. 

So to split the difference, I've added a new "Seed and Int" node under the "numbers" category that outputs the numbers as both a SEED type and Int type.

**Comment by JHNewton** [comment]
OK, I'll check it out.  It's been close to 20 years since I've done any
programming, but I don't remember a "seed" type of variable.  Int and
float, yes, but not seed.  Oh well, new day, new stuff.  BTW, where do you
save the data from the metadata/prompt save node.  It's not showing up in
the output folder.

Thanks

Regards,
John Newton

Fotographixs <http://www.fotographixs.com>
Instagram <https://instagram.com/john.fotographixs/>
Facebook <https://www.facebook.com/profile.php?id=1240206692>

I don't think that I'll ever reach the stage when I will say, "This is what
I believe. Finished." What I believe is alive ... and open to growth.
                                          --Madeleine L'Engle

**Comment by wallish77** [comment]
There's two nodes that do something similar but with different outputs for the metadata: The "Image Save with Prompt Data" stores the metadata inside the image file like Automatic1111 does.  For JPEG it will be in the exif data, and for PNG it will be in the comment.    "Image Save with Prompt File" is a node that is very similar but writes the metadata to a text file with the same name as the image save.
